### ISSUE TITLE
Incorrect "winner" algorithm

### ISSUE THREAD

**Issue by nick-ng** [jackyzhen/coffee-tracker#1]
The "winner" is not correctly selected.
<img width="777" alt="screen shot 2016-09-09 at 9 44 03 am" src="https://cloud.githubusercontent.com/assets/17075261/18368071/261697e2-7672-11e6-9cc9-fdd5aa033a74.png">
In this situation, the net coffees paid for are:
Milos: -1
Jacky: 0
Nick: 3
Giang: -2
So Giang should be the "winner". The app selects Jacky instead.

**Comment by nick-ng** [comment]
The coffees drank to paid ratios are:
Milos: 1.25
Jacky: 1
Nick: 0.625
Giang: 1.667
So it should still be Giang

**Comment by jackyzhen** [comment]
#3 
This is fixed in latest commit.
